apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your_email@example.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        route53:
          hostedZoneID: XXXXXXXXXXXXXXXXXXXX
          region: us-east-2
      selector:
        dnsZones:
        - "lab.example.com"
    - http01:
        ingress:
          class: nginx